language: java
jdk:
- oraclejdk11
# git strips the wrapper jar file so we have to force its download during the build
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

deploy:
 provider: heroku
 api-key: 
  secure: 2eb426fe-bbac-4700-a545-e0ca3fcf9baf
 app: dj-spring-boot